import { expect,it } from 'vitest'
import { calculateBudget } from '../domain/calculations/budget'
import { xinjiangFuelRounding,xinjiangSeed } from '../fixtures/xinjiang/seed'
import { xinjiangSourceConflicts } from '../fixtures/xinjiang/conflicts'
it('X01 imports 10 days, 9 nights, placeholder people, groups and vehicle',()=>{expect(xinjiangSeed.days).toHaveLength(10);expect(new Set(xinjiangSeed.roomNights.map(r=>r.date))).toHaveLength(9);expect(xinjiangSeed.participants).toHaveLength(3);expect(xinjiangSeed.groups).toHaveLength(2);expect(xinjiangSeed.vehicles).toHaveLength(1)})
it('X02 reproduces lodging totals and inferred room nights',()=>{expect(xinjiangSeed.roomNights.reduce((s,r)=>s+(r.priceFen??0),0)).toBe(1130968);expect(xinjiangSeed.roomNights.filter(r=>r.occupantIds.includes('x-p3')).reduce((s,r)=>s+(r.priceFen??0),0)).toBe(522034);expect(xinjiangSeed.roomNights.filter(r=>r.occupantIds.includes('x-p1')).reduce((s,r)=>s+(r.priceFen??0),0)).toBe(608934);expect(xinjiangSeed.roomNights.filter(r=>r.certainty==='inferred').map(r=>r.date)).toEqual(['2026-10-02','2026-10-02','2026-10-03','2026-10-03'])})
it('X03 does not invent a zero-price third-person booking on Oct 4',()=>{expect(xinjiangSeed.roomNights.filter(r=>r.date==='2026-10-04')).toHaveLength(1);expect(xinjiangSeed.roomNights.find(r=>r.date==='2026-10-04')!.occupantIds).not.toContain('x-p3')})
it('X04 separates purchased tickets from actual paid expenses',()=>{expect(xinjiangSeed.bookings.filter(b=>b.purchaseStatus==='purchased').reduce((s,b)=>s+(b.totalPriceFen??0),0)).toBe(100500);expect(xinjiangSeed.budgetItems.find(i=>i.id==='x-budget-ticket')!.highFen).toBe(190500);expect(xinjiangSeed.expenses).toHaveLength(0)})
it('X05 and X06 preserve rounding and incomplete budget totals',()=>{expect(xinjiangFuelRounding.formulaFen).toEqual({low:273874,high:414960});expect(xinjiangFuelRounding.guideBudgetFen).toEqual({low:273900,high:415000});expect(calculateBudget(xinjiangSeed.budgetItems)).toEqual({lowFen:1956168,highFen:2097268,unknownCount:2,complete:false})})
it('imports all source conflicts without auto-confirmation',()=>{expect(xinjiangSourceConflicts.map(c=>c.code)).toEqual(['C01','C02','C03','C04','C05','C06','C07','C08','C09','C10']);expect(xinjiangSourceConflicts.every(c=>!c.userConfirmed)).toBe(true)})
